/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "labrpc.h"
#define MAXVET 500000

float *
max_100_svc(vetor *argp, struct svc_req *rqstp)
{
	static float  result;

	int i;
	float n = argp->v[0];
	for(i = 1; i < MAXVET; i++) {
		if(argp->v[i] > n)
			n = argp->v[i];
	}
	result = n;

	return &result;
}

float *
min_100_svc(vetor *argp, struct svc_req *rqstp)
{
	static float  result;

	int i;
	float n;
	n = argp->v[0];
	for(i = 1; i < MAXVET; i++) {
		if(argp->v[i] < n)
			n = argp->v[i];
	}
	result = n;

	return &result;
}
