/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "labrpc.h"
#include <stdio.h>
#include <math.h> //para elevar ao quadrado e tirar raiz
#include <time.h>

#define MAXVET 50

void init_vet ();
float f_aleat(int );  


// void
// entrega1_100(char *host)
// {
// 	CLIENT *clnt;
// 	float  *result_1;
// 	float  max_100_arg;
// 	float  *result_2;
// 	float  min_100_arg;

// #ifndef	DEBUG
// 	clnt = clnt_create (host, ENTREGA1, VERSAO, "udp");
// 	if (clnt == NULL) {
// 		clnt_pcreateerror (host);
// 		exit (1);
// 	}
// #endif	/* DEBUG */

// 	result_1 = max_100(&max_100_arg, clnt);
// 	if (result_1 == (float *) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// 	result_2 = min_100(&min_100_arg, clnt);
// 	if (result_2 == (float *) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// #ifndef	DEBUG
// 	clnt_destroy (clnt);
// #endif	 /* DEBUG */
// }

vetor vet;

int
main (int argc, char *argv[])
{
	CLIENT *clnt;
	char *host;

	// if (argc < 2) {
	// 	printf ("usage: %s server_host\n", argv[0]);
	// 	exit (1);
	// }
	// host = argv[1];
	// entrega1_100 (host);

	clnt = clnt_create(argv[1], ENTREGA1, VERSAO, "udp");
	/* Garantindo a criacao da ligacao com o remoto */
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1); 
	}

	//semente para gerar rand
	srand(time(0));

	// variaveis
	float server_reply[2];

	// Inicializar vetor
	init_vet();

	// imprime vetor
	for (int i = 0; i < MAXVET; i++) {
		printf("%0.2f\n", vet.v[i]);
	}

	/* Chama o stub cliente criado pelo rpcgen */
	server_reply[0] = *(min_100(&vet,clnt));
	if (server_reply==NULL) {
		fprintf(stderr,"Problema na chamada RPC\n");
	exit(0); 
	}

	/* Chama o stub cliente criado pelo rpcgen */
	server_reply[1] = *(max_100(&vet,clnt));
	if (server_reply==NULL) {
		fprintf(stderr,"Problema na chamada RPC\n");
	exit(0); 
	}

	//Escrevendo resposta do servidor
	puts("Server reply :\n");
	for (int i = 0; i < 2; i++) {
		printf("%0.2f\n", server_reply[i]);
	}

	// return(*server_reply);

exit (0);
}

// Gera um valor aleatorio entre 0 e X
float f_aleat(int X) {
	return rand() % X;
}

// inicializa o vetor
void init_vet () {
  for (int i = 0; i < MAXVET; i++) {
		vet.v[i] = pow((i+1) - (f_aleat(MAXVET)/2), 2); 
  }
	for (int i = 0; i < MAXVET; i++) { 
		vet.v[i] = sqrt(vet.v[i]);
  }
}
