/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "labrpc.h"
#include <stdio.h>
#include <math.h> //para elevar ao quadrado e tirar raiz
#include <time.h>

#define MAXVET 500000

void init_vet ();
float f_aleat(int );  

vetor vet;

int
main (int argc, char *argv[])
{
	CLIENT *clnt;
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	clnt = clnt_create(argv[1], ENTREGA1, VERSAO, "tcp");
	/* Garantindo a criacao da ligacao com o remoto */
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1); 
	}

	//semente para gerar rand
	srand(time(0));

	// variaveis
	float server_reply[2];

	// Inicializar vetor
	init_vet();

	/* Chama o stub cliente criado pelo rpcgen */
	server_reply[0] = *(min_100(&vet,clnt));
	if (server_reply==NULL) {
		fprintf(stderr,"Problema na chamada RPC\n");
	exit(0); 
	}


	/* Chama o stub cliente criado pelo rpcgen */
	server_reply[1] = *(max_100(&vet,clnt));
	if (server_reply==NULL) {
		fprintf(stderr,"Problema na chamada RPC\n");
	exit(0); 
	}

	//Escrevendo resposta do servidor
	puts("Server reply :\n");
	printf("Menor: %0.2f\n", server_reply[0]);
	printf("Maior: %0.2f\n", server_reply[1]);

exit (0);
}

// Gera um valor aleatorio entre 0 e X
float f_aleat(int X) {
	return rand() % X;
}

// inicializa o vetor
void init_vet () {
  for (int i = 0; i < MAXVET; i++) {
		vet.v[i] = pow((i+1) - (f_aleat(MAXVET)/2), 2); 
  }
	for (int i = 0; i < MAXVET; i++) { 
		vet.v[i] = sqrt(vet.v[i]);
  }
}
